# tests/test_auth.py - 认证功能简单测试
print("=== 用户认证系统测试 ===")
print()
print("测试步骤：")
print("1. 启动Flask服务器: python run.py")
print("2. 打开浏览器访问: http://localhost:5000")
print("3. 点击'去登录'链接")
print("4. 使用以下测试账户登录:")
print("   - 学生: zhangsan / 123456")
print("   - 教师: zhang_prof / 123456")
print("   - 管理员: admin / 123456")
print()
print("5. 测试功能:")
print("   - 登录后查看个人资料页面")
print("   - 测试不同角色的权限页面")
print("   - 测试注销功能")
print()
print("预期结果：")
print("- 学生只能访问 /student/dashboard")
print("- 教师只能访问 /teacher/dashboard")
print("- 管理员可以访问所有页面")
print("- 未登录时访问受限页面会跳转到登录")