# tests/test_student.py - 学生管理功能测试指南
print("=== 学生管理模块测试指南 ===")
print()
print("测试步骤：")
print("1. 确保Flask服务器正在运行")
print("2. 使用学生账号登录")
print("3. 访问学生仪表板: http://localhost:5000/student/dashboard")
print()
print("需要测试的功能：")
print("✅ 个人资料查看（含敏感信息解密）")
print("✅ 可选课程列表显示")
print("✅ 选课功能")
print("✅ 已选课程查看")
print("✅ 退选功能")
print("✅ 成绩查询（含完整性验证）")
print()
print("预期结果：")
print("- 身份证和手机号应正确解密显示")
print("- 选课/退课应实时更新课程容量")
print("- 成绩页面应显示完整性验证状态")
print("- 所有操作应有日志记录")